version: "3"
services:
    mongodb:
        image: mongo
        ports:
            - ${MONGO_PORT}:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME:${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD:${MONGO_INITDB_ROOT_PASSWORD}
            #- MONGO_INITDB_ROOT_PASSWORD_FILE=.env,
        extra_hosts:
            - "mongo_host:${MONGO_HOST}"
